# TL Labs Caldera Local Configuration
# This file overrides settings from default.yml
# DO NOT commit this file (it's in .gitignore)

# ============================================
# Orchestrator Plugin Configuration
# ============================================
# ⚠️ SECURITY: Set ELK credentials via environment variables:
#   export ELK_URL="http://20.28.49.97:9200"
#   export ELK_USER="elastic"
#   export ELK_PASS="your-password-here"
# Or use .env file (see .env.example)

plugins:
  orchestrator:
    # Elasticsearch / ELK Stack Settings
    # elk_url loaded from ELK_URL env var
    elk_index: "purple-team-logs"
    
    # Authentication (set via env vars for security)
    # elk_api_key: ""  # Generate: POST /_security/api_key
    # elk_user/elk_pass loaded from ELK_USER/ELK_PASS env vars
    
    # Connection settings
    elk_verify_ssl: false
    elk_connection_timeout: 30
    elk_max_retries: 3

# Legacy elk config (deprecated - use plugins.orchestrator.elk_* instead)
elk:
  url: http://20.28.49.97:9200
  index: purple-team-logs
  api_key: ""
  verify_ssl: false
  connection_timeout: 30
  max_retries: 3

# Enable plugins
plugins:
  - sandcat
  - stockpile
  - atomic
  - magma
  - orchestrator  # ✨ TL Labs Purple Team Automation
  - reporting
  - debrief  # MITRE debrief plugin
  - debrief-elk-detections  # ELK detection coverage for debrief
  - branding
